services:
  db:
    image: "postgres:14"
    container_name: "chipless-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chipless
    ports:
      - "54321:5432"
